import StytchProvider from "./components/StytchProvider"
import { MantineProvider, AppShell } from "@mantine/core"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <MantineProvider withGlobalStyles withNormalizeCSS>
          <AppShell>
            <StytchProvider children={children} >
              {children}
            </StytchProvider>
          </AppShell>
        </MantineProvider>
    )
  }