services:
  iterative_backend:
    container_name: iterative_backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  iterative_frontend:
    container_name: iterative_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env

  iterative_backend_modules:
    container_name: iterative_backend_modules
    build: ./backend-modules
    ports:
      - "8080:8080"
    env_file:
      - backend-modules/.env
