services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local

  backend-modules:
    build: ./backend-modules
    ports:
      - "8080:8080"
    env_file:
      - ./backend-modules/.env
